package: template_manager
version: '1.3.0'
author: FriendsOfREDAXO
supportpage: https://github.com/FriendsOfREDAXO/template_manager

page:
    title: 'Template Manager'
    perm: template_manager[]
    icon: rex-icon fa-file-text
    subpages:
        settings:
            title: 'translate:template_manager_settings'
            icon: rex-icon fa-sliders
        config:
            title: 'translate:template_manager_configure'
            icon: rex-icon fa-edit
            hasLayout: true
            hidden: true
        setup:
            title: 'Setup'
            icon: rex-icon fa-wrench
            perm: admin
        help: { title: 'translate:help', subPath: README.md, itemClass: 'pull-right' }

requires:
    redaxo: '^5.17'
    php:
        version: '^8.0'
    packages:
        yrewrite: '>=2.0'
